# -*- coding: utf-8 -*-
"""AnomalyDetection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mA0C_qMfprWC2ikxyBC71bPvJLq11cZN
"""

# Installing and import necessary libraries
!pip install adtk

import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf

from adtk.data import validate_series
from adtk.visualization import plot
from adtk.detector import ThresholdAD, QuantileAD, InterQuartileRangeAD, GeneralizedESDTestAD, PersistAD, VolatilityShiftAD, CustomizedDetectorHD

# Load data
s_train = pd.read_csv("temperature.csv", parse_dates=True, squeeze=True)
s_train["Date"] = pd.to_datetime(s_train["Date"])
s_train = s_train.set_index("Date")
s_train = s_train['Mean']

s_train = yf.download("AAPL")['Close']

s_train = validate_series(s_train)
print(s_train)

# Plot temperature or AAPL stock price
plot(s_train)
plt.show()

# Threshold Anomaly Detection (detect anomalies based on thresholds)
threshold_ad = ThresholdAD(high=0.75, low=-0.5)
anomalies = threshold_ad.detect(s_train)
plot(s_train, anomaly=anomalies, anomaly_color="red", anomaly_tag="marker")
plt.show()

# Quantile Anomaly Detection (detect anomalies based on percentiles)
quantile_ad = QuantileAD(high=0.99, low=0.01)
anomalies = quantile_ad.fit_detect(s_train)
plot(s_train, anomaly=anomalies, ts_linewidth=1, ts_markersize=3, anomaly_markersize=5, anomaly_color='red', anomaly_tag="marker")
plt.show()

# Inter Quartile Range Anomaly Detection (detect anomalies based on IQR)
iqr_ad = InterQuartileRangeAD(c=1.5)
anomalies = iqr_ad.fit_detect(s_train)
plot(s_train, anomaly=anomalies, ts_linewidth=1, ts_markersize=3, anomaly_markersize=5, anomaly_color='red', anomaly_tag="marker")
plt.show()

# Generalized Extreme Studentized Deviate (ESD) Test (detect anomalies assuming normal distribution)
esd_ad = GeneralizedESDTestAD(alpha=0.3)
anomalies = esd_ad.fit_detect(s_train)
plot(s_train, anomaly=anomalies, ts_linewidth=1, ts_markersize=3, anomaly_markersize=5, anomaly_color='red', anomaly_tag="marker")
plt.show()

# Persist Anomaly Detection (detect persistent changes)
persist_ad = PersistAD(c=3.0, side='positive')
anomalies = persist_ad.fit_detect(s_train)
plot(s_train, anomaly=anomalies, ts_linewidth=1, ts_markersize=3, anomaly_color='red')
plt.show()

persist_ad = PersistAD(c=1.5, side='negative')
anomalies = persist_ad.fit_detect(s_train)
plot(s_train, anomaly=anomalies, ts_linewidth=1, ts_markersize=3, anomaly_color='red')
plt.show()

persist_ad.window = 24  # by default just one day, we can adjust it for mid- to long-term detection
anomalies = persist_ad.fit_detect(s_train)
plot(s_train, anomaly=anomalies, ts_linewidth=1, ts_markersize=3, anomaly_color='red')
plt.show()

# Volatility Shift Anomaly Detection (detect volatility shifts)
s_train = yf.download("TSLA")['Close']
s_train = validate_series(s_train)

volatility_shift_ad = VolatilityShiftAD(c=6.0, side='positive', window=30)
anomalies = volatility_shift_ad.fit_detect(s_train)
plot(s_train, anomaly=anomalies, anomaly_color='red')
plt.show()

